controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_create:
    path: /users/create
    controller: App\Controller\UserController::addUser
    methods: [POST]
user_list:
    path: /user
    controller: App\Controller\UserController::addUser
    methods: [GET]
user_delete:
    path: /users/{id}/delete
    controller: App\Controller\UserController::deleteUser
    methods: [POST]